name: github-test
on: push
jobs:
  my_first_job:
    name: My first job
    runs-on: macOS-latest
    steps:
      - name: Print a greeting
        run: echo `pwd`
      - name: Print 2
        run: ls -alh
      - name: Print 3
        run: ls -alh ../
