name: github-test
on: push
jobs:
  my_first_job:
    name: My first job
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Print a greeting
        run: echo `pwd`
      - name: Print 2
        run: ls -alh
      - name: Print 3
        run: ls -alh ../
